first.exe:
	cl /EHsc first.cpp

avl.exe: 
	cl /EHsc avl.cpp
	
bst.exe:
	cl /EHsc bst.cpp
	
hash1.exe:
	cl /EHsc hash1.cpp
	
hash2.exe:
	cl /EHsc hash2.cpp
	
hashmap.exe:
	cl /EHsc hashmap.cpp
	
unorderedmap.exe:
	cl /EHsc unorderedmap.cpp
	
Clean: 
	del *.obj 
	del *.exe