cl /EHsc d3dtest.cpp /I "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include" /link /LIBPATH:"C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86" 

cl /EHsc GLfirst.cpp /I "E:\glfw-3.3.2.bin.WIN64\include" /link /LIBPATH:"E:\glfw-3.3.2.bin.WIN64\lib-vc2019" 

cl /EHsc SDLFirst.cpp /I "E:\SDL2-devel-2.0.12-VC\SDL2-2.0.12\include" /link /LIBPATH:"E:\SDL2-devel-2.0.12-VC\SDL2-2.0.12\lib\x64" 