print("Hello World.")

print(type(10.4*3))       
print(type("Hello world"))
print(type(print))        
print(type(type))         
print(type(true))         
print(type(nil))          
print(type(X)) 
print(type(type(X)))      